# Generated by Django 5.0.3 on 2024-03-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_quillpost_date_quillpost_description_quillpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quillpost',
            name='description',
            field=models.TextField(default='No description', unique=True),
        ),
        migrations.AlterField(
            model_name='quillpost',
            name='title',
            field=models.CharField(default='No title', max_length=150, unique=True),
        ),
    ]
