# Generated by Django 5.0.3 on 2024-03-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_quillpost_description_alter_quillpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quillpost',
            name='description',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='quillpost',
            name='title',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
