# Generated by Django 5.0.3 on 2024-03-19 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_quillpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quillpost',
            name='image',
        ),
        migrations.AddField(
            model_name='quillpost',
            name='image_url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
