# Generated by Django 5.0.3 on 2024-03-19 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_quillpost_image_quillpost_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quillpost',
            name='image_url',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
