# Generated by Django 5.0.3 on 2024-03-21 03:26

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_quillpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quillpost',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
