# Generated by Django 5.0.3 on 2024-03-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_quillpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quillpost',
            name='description',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
